obj-$(CONFIG_POWER_AVS)		+= avs/
obj-$(CONFIG_POWER_RESET)	+= reset/
obj-$(CONFIG_POWER_SUPPLY)	+= supply/
#ifdef CONFIG_MACH_REALME_TRINKET
#/* Zhangchangan  PSW.BSP.CHG  2019-10-30 */
obj-$(CONFIG_MACH_REALME_TRINKET)	+= oppo/
#endif
